fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: secured_area
  user_class: App\Entity\User
  from_email:
    address: "hello@example.com"
    sender_name: "Jean Jacques"
