hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

github_login:
    path: /login/check-github

github_connect:
    path: /connect/github

bagarre_bundle:
    resource: '@AppBundle/Resources/config/routing.yml'

logout:
   path: /logout
