services:
  # Repositories
  App\Domain\Repository\PlayerRepositoryInterface: '@App\Infrastructure\Persistence\Sql\Player\SqlPlayerRepository'
  App\Domain\Repository\GameRepositoryInterface: '@App\Infrastructure\Persistence\Sql\Game\SqlGameRepository'
  App\Domain\Repository\CharacterRepositoryInterface: '@App\Infrastructure\Persistence\Sql\Character\SqlCharacterRepository'
  App\Domain\Repository\PlanetRepositoryInterface: '@App\Infrastructure\Persistence\Sql\Planet\SqlPlanetRepository'

  # Queries
  App\Domain\Query\Player\PlayerHasActiveCharacterInterface: '@App\Infrastructure\Persistence\Sql\Player\SqlPlayerHasActiveCharacter'
  App\Domain\Query\Game\FindAllGamesWaitingForPlayerInterface: '@App\Infrastructure\Persistence\Sql\Game\SqlFindAllGamesWaitingForPlayer'
  App\Domain\Query\Game\GameExistsInterface: '@App\Infrastructure\Persistence\Sql\Game\SqlGameExists'
  App\Domain\Query\Game\IsGameWaitingForPlayerInterface: '@App\Infrastructure\Persistence\Sql\Game\SqlIsGameWaitingForPlayer'
  App\Domain\Query\Character\CountCharactersByGameInterface: '@App\Infrastructure\Persistence\Sql\Character\SqlCountCharactersByGame'
  App\Domain\Query\Character\FindCharactersDetailsByGameInterface: '@App\Infrastructure\Persistence\Sql\Character\SqlFindCharactersDetailsByGame'
