App\Application\Game\CreateGameCommand:
    constraints:
        - App\Infrastructure\Validation\Game\PlayerShouldNotHaveActiveCharacter: ~

App\Application\Player\PlayerJoinsRandomGameCommand:
    constraints:
        - App\Infrastructure\Validation\Game\PlayerShouldNotHaveActiveCharacter: ~
