# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-apache-node
      - image: circleci/mysql:5.7.23
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: kork_test
          MYSQL_USER: kork_test
          MYSQL_PASSWORD: kork_test
          MYSQL_ROOT_HOST: 127.0.0.1

    working_directory: ~/kork

    steps:
      - checkout

      - run: sudo apt-get update
      - run: sudo apt install -y mysql-client
      - run: sudo docker-php-ext-install pdo_mysql

      # Download and cache dependencies
      - restore_cache:
          keys:
              - v1-dependencies-{{ checksum "composer.json" }}
              # fallback to using the latest cache if no exact match is found
              - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
              - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run: bin/console kork:schema:create --env=test
      - run: bin/console doctrine:schema:create --env=test

      # TESTS
      - run: vendor/bin/phpspec run -c tests/phpspec.yml.dist tests/spec
      - run: vendor/bin/simple-phpunit
