login:
    path: /login
    controller: App\Infrastructure\Controller\Lobby\LogginAction::handle

logout:
    path: /logout

lobby:
    path: /lobby
    controller: App\Infrastructure\Controller\Lobby\LobbyAction::handle

index:
    path: /
    controller: App\Infrastructure\Controller\Lobby\IndexAction::handle

join_random_game:
    path: /game/join
    controller: App\Infrastructure\Controller\Lobby\JoinRandomGameAction::handle

join_game:
    path: /game/join/{gameId}
    controller: App\Infrastructure\Controller\Lobby\JoinGameAction::handle
