parameters:
    kork.app_bundle.doctrine.saver.base.class: AppBundle\Doctrine\Saver\BaseSaver


services:
    kork.app_bundle.game.saver:
        class: '%kork.app_bundle.doctrine.saver.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'AppBundle\Entity\Game'

    kork.app_bundle.character.saver:
        class: '%kork.app_bundle.doctrine.saver.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'AppBundle\Entity\Character'
