parameters:
    kork.bundle.app_bundle.user.user_provider.class: Kork\Bundle\AppBundle\User\FOSUBUserProvider

services:
    kork.bundle.app_bundle.user.user_provider:
        class: "%kork.bundle.app_bundle.user.user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments:
            - '@fos_user.user_manager'
            - { github: github_id }
