AppBundle\Entity\Game:
    type:  entity
    table: kork_game
    repositoryClass: AppBundle\Doctrine\Repository\GameRepository
    fields:
        id:
            id: true
            type: guid
            generator:
                strategy: UUID
        date_creation:
            type: date
            nullable: true
