AppBundle\Entity\Game:
    type:  entity
    table: kork_game
    fields:
        id:
            id: true
            type: guid
            generator:
                strategy: UUID
        date_creation:
            type: date
            nullable: true
    oneToMany:
        characters:
            targetEntity: AppBundle\Entity\Character
            mappedBy: game
            cascade:
                - persist
                - detach
                - remove
            orphanRemoval: true
